version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hubi_tickets_app
    container_name: tickets_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - hubi_net
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hubi_tickets
      MYSQL_USER: hubi_user
      MYSQL_PASSWORD: Hub*tIckeT5
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - hubi_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hubi_net

  nginx:
    image: nginx:alpine
    container_name: hubi_nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx/docker_default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - hubi_net